### ISSUE TITLE
es6

### ISSUE THREAD

**Issue by JAertgeerts** [hunterloftis/jackrabbit#81]
drop support for node 4 and lower

**Comment by matmar10** [comment]
What benefit will the project get by dropping support for node 4? I'm closing this one as wontfix. Feel free to open if there is a prescient need

**Comment by JAertgeerts** [comment]
Use es6 syntax is the header :)

**Comment by matmar10** [comment]
Right I saw that, but I don't see how this is related to an urgent or
important need. There's nothing gained by moving the project syntax to ES6
syntax other than creating work for someone to change the code.

If this is blocking addition of something super important, then let's
prioritize it. Otherwise let's leave it as-is.

________________
Matthew J. Martin

*Schedule a meeting here ---> *calendly.com/matmar10

WhatsApp: +14156014879

Indonesia: (0)811 553 3324
US: (307) 461-9929

G+: Matthew.Mar10 | Skype: MatMar10
